LIQUID-TRAP-MIB DEFINITIONS ::= BEGIN
        IMPORTS zimbra FROM LIQUID-MIB;

lqtraps OBJECT IDENTIFIER ::= { zimbra 0 }

lqServiceStatusTrap NOTIFICATION-TYPE
        STATUS current
        DESCRIPTION "Service Status Change"
        ::= { lqtraps 0 }

END               
