@REPOS = (
   { name => "zm-admin-help-network",               branch => "master",          user => "zimbra" },
   { name => "zm-archive-utils",                    branch => "dev",             user => "zimbra" },
   { name => "zm-backup-store",                     branch => "dev",             user => "zimbra" },
   { name => "zm-backup-utilities",                 branch => "master",          user => "zimbra" },
   { name => "zm-convertd-native",                  branch => "master",          user => "zimbra" },
   { name => "zm-downloads",                        branch => "master",          user => "zimbra" },
   { name => "zm-ews-store",                        branch => "dev",             user => "zimbra" },
   { name => "zm-ews-stub",                         branch => "dev",             user => "zimbra" },
   { name => "zm-hsm",                              branch => "master",          user => "zimbra" },
   { name => "zm-hsm-store",                        branch => "master",          user => "zimbra" },
   { name => "zm-license-tools",                    branch => "dev",             user => "zimbra" },
   { name => "zm-licenses",                         branch => "master",          user => "zimbra" },
   { name => "zm-network-store",                    branch => "master",          user => "zimbra" },
   { name => "zm-rebranding-docs",                  branch => "master",          user => "zimbra" },
   { name => "zm-saml-consumer-store",              branch => "master",          user => "zimbra" },
   { name => "zm-sync-store",                       branch => "dev",             user => "zimbra" },
   { name => "zm-sync-tools",                       branch => "dev",             user => "zimbra" },
   { name => "zm-touch-client",                     branch => "master",          user => "zimbra" },
   { name => "zm-twofactorauth-store",              branch => "dev",             user => "zimbra" },
   { name => "zm-voice-store",                      branch => "dev",             user => "zimbra" },
   { name => "zm-windows-comp",                     branch => "dev",             user => "zimbra" },
);
