"""
Zimbra VA build components.
"""

CSC_UBUNTU804_BRANCH = 'main'
CSC_UBUNTU804_CLN = 5042
CSC_UBUNTU804_BUILDTYPE = 'release'

VA_BUILD_BRANCH = 'main'
VA_BUILD_CLN = 37254
VA_BUILD_BUILDTYPE = 'release'

TOOLS_BRANCH = 'esx-klnext'
TOOLS_CLN = 1047652
TOOLS_BUILDTYPE = 'release'
