#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
# Exit strings available are 17-31 with bits 5 and 6 set to 1.
# 16 = 112
# 17 = 113
# 18 = ... 
echo "Performing installation check"

for i in core mta store ldap snmp logger apache spell; do
	echo -n "Looking for $i..."
	pkgs=`find /Library/Receipts/zimbra-${i}* -type d -maxdepth 0 | sort -r`
	first=1
	for pkg in $pkgs; do
    if [ -f "${pkg}/Contents/Info.plist" ]; then
      VER=`grep -C1 CFBundleGetInfoString ${pkg}/Contents/Info.plist | tail -1 | sed -e 's/\<[^>]*\>//g' -e 's/^ *//g' | awk -F, '{print $1}' | awk '{print $1}'`
    fi
		echo "found $VER."
		if [ $first -ne 1 ]; then
			echo "Removing $pkg"
			/bin/rm -rf $pkg
		fi
		first=2
	done
done

exit 0
