#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.zimbra.com/license
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is: Zimbra Collaboration Suite Server.
# 
# The Initial Developer of the Original Code is Zimbra, Inc.
# Portions created by Zimbra are Copyright (C) 2006 Zimbra, Inc.
# All Rights Reserved.
# 
# Contributor(s):
# 
# ***** END LICENSE BLOCK *****
# 

echo "Performing installation check"

for i in core mta store ldap snmp logger apache spell; do
	echo "Looking for $i"
	pkgs=`find /Library/Receipts/zimbra-${i}* -type d -maxdepth 0 | sort -r`
	first=1
	for pkg in $pkgs; do
		echo "Found $pkg"
		if [ $first -ne 1 ]; then
			echo Removing $pkg
			/bin/rm -rf $pkg
		fi
		first=2
	done
done

GOOD=yes
echo "Getting for required space..."
# /tmp must have 1GB
# /opt/zimbra must have 5GB
#!/bin/bash
TMPKB=`df -lk /tmp | tail -1 | awk '{print $4}'`
AVAIL=$(($TMPKB / 1048576))
if [ $AVAIL -lt  1 ]; then
  echo "/tmp must have at least 1GB of availble space to install."
  echo "${AVAIL}GB is not enough space to install ZCS."
  GOOD=no
fi

ZIMBRA=`df -k /opt/zimbra | tail -1 | awk '{print $4}'`
AVAIL=$(($ZIMBRA / 1048576))
if [ $AVAIL -lt 5 ]; then
  echo "/opt/zimbra requires at least 5GB of space to install."
  echo "${AVAIL}GB is not enough space to install."
  GOOD=no
fi
if [ $GOOD = "no" ]; then
  echo ""
  echo "Installation cancelled."
  echo ""
  exit 113
fi

exit 0
