#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2007, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
# Exit strings available are 17-31 with bits 5 and 6 set to 1.
# 16 = 48
# 17 = 113
# 18 = ... 
GOOD=yes
SCP_PATH=$0
VOL_PATH=$1

echo "Checking for required space..."
# /tmp must have 1GB
# /opt/zimbra must have 5GB
TMPKB=`df -lk /tmp | tail -1 | awk '{print $4}'`
AVAIL=$(($TMPKB / 1048576))
if [ $AVAIL -lt  1 ]; then
  echo "/tmp must have at least 1GB of availble space to install."
  echo "${AVAIL}GB is not enough space to install ZCS."
  GOOD=no
fi

if [ -d "$VOL_PATH/opt/zimbra" ]; then
  PART_CHECK="$VOL_PATH/opt/zimbra";
else
  PART_CHECK="$VOL_PATH/"
fi
ZIMBRA=`df -k $PART_CHECK | tail -1 | awk '{print $4}'`
AVAIL=$(($ZIMBRA / 1048576))
if [ $AVAIL -lt 5 ]; then
  echo "/opt/zimbra requires at least 5GB of space to install."
  echo "${AVAIL}GB is not enough space to install."
  GOOD=no
fi
if [ $GOOD = "no" ]; then
  if [ -f "$VOL_PATH/opt/zimbra/.skipvolcheck" ]; then
    exit 0
  fi
  echo ""
  echo "Installation cancelled."
  echo ""
  exit 48
fi

exit 0
