# vi:ft=dockerfile
FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

# SYSTEM
RUN apt-get -qq update
RUN apt-get -qq dist-upgrade -y
RUN apt-get -qq autoremove -y
RUN apt-get -qq install -y apt-utils
RUN apt-get -qq install -y ca-certificates tzdata
RUN apt-get -qq install -y curl wget
RUN apt-get -qq install -y software-properties-common
RUN apt-get -qq install -y sudo

# ENVIRONMENT
RUN apt-get -qq install -y git perl ruby
RUN apt-get -qq install -y openssh-client
RUN apt-get -qq install -y rsync
RUN apt-get -qq install -y awscli

# USERS
RUN useradd -ms /bin/bash -G sudo ubuntu

# REDUCE PRIVILEGE
USER ubuntu
WORKDIR /home/build
