our $BUILD_BRANCH = "develop";

@ENTRIES = (
   { name => "ant-1.7.0-ziputil-patched",           branch => $BUILD_BRANCH, },
   { name => "ant-tar-patched",                     branch => $BUILD_BRANCH, },
   { name => "ical4j-0.9.16-patched",               branch => $BUILD_BRANCH, },
   { name => "junixsocket",                         tag    => "junixsocket-parent-2.0.4", remote => "gh-ks" },
   { name => "nekohtml-1.9.13",                     branch => $BUILD_BRANCH, },
   { name => "zm-admin-console",                    branch => $BUILD_BRANCH, },
   { name => "zm-admin-help-common",                branch => $BUILD_BRANCH, },
   { name => "zm-ajax",                             branch => $BUILD_BRANCH, },
   { name => "zm-amavis",                           branch => $BUILD_BRANCH, },
   { name => "zm-aspell",                           branch => $BUILD_BRANCH, },
   { name => "zm-bulkprovision-admin-zimlet",       branch => $BUILD_BRANCH, },
   { name => "zm-bulkprovision-store",              branch => $BUILD_BRANCH, },
   { name => "zm-certificate-manager-admin-zimlet", branch => $BUILD_BRANCH, },
   { name => "zm-certificate-manager-store",        branch => $BUILD_BRANCH, },
   { name => "zm-charset",                          branch => $BUILD_BRANCH, },
   { name => "zm-clam-scanner-store",               branch => $BUILD_BRANCH, },
   { name => "zm-clientuploader-admin-zimlet",      branch => $BUILD_BRANCH, },
   { name => "zm-clientuploader-store",             branch => $BUILD_BRANCH, },
   { name => "zm-core-utils",                       branch => $BUILD_BRANCH, },
   { name => "zm-db-conf",                          branch => $BUILD_BRANCH, },
   { name => "zm-dnscache",                         branch => $BUILD_BRANCH, },
   { name => "zm-downloads",                        branch => $BUILD_BRANCH, },
   { name => "zm-freshclam",                        branch => $BUILD_BRANCH, },
   { name => "zm-help",                             branch => $BUILD_BRANCH, },
   { name => "zm-helptooltip-zimlet",               branch => $BUILD_BRANCH, },
   { name => "zm-jetty-conf",                       branch => $BUILD_BRANCH, },
   { name => "zm-jython",                           branch => $BUILD_BRANCH, },
   { name => "zm-launcher",                         branch => $BUILD_BRANCH, },
   { name => "zm-ldap-utilities",                   branch => $BUILD_BRANCH, },
   { name => "zm-ldap-utils-store",                 branch => $BUILD_BRANCH, },
   { name => "zm-licenses",                         branch => $BUILD_BRANCH, },
   { name => "zm-mailbox",                          branch => $BUILD_BRANCH, },
   { name => "zm-migration-tools",                  branch => $BUILD_BRANCH, },
   { name => "zm-mta",                              branch => $BUILD_BRANCH, },
   { name => "zm-nginx-conf",                       branch => $BUILD_BRANCH, },
   { name => "zm-nginx-lookup-store",               branch => $BUILD_BRANCH, },
   { name => "zm-openid-consumer-store",            branch => $BUILD_BRANCH, },
   { name => "zm-postfix",                          branch => $BUILD_BRANCH, },
   { name => "zm-proxy-config-admin-zimlet",        branch => $BUILD_BRANCH, },
   { name => "zm-taglib",                           branch => $BUILD_BRANCH, },
   { name => "zm-timezones",                        branch => $BUILD_BRANCH, },
   { name => "zm-versioncheck-admin-zimlet",        branch => $BUILD_BRANCH, },
   { name => "zm-versioncheck-store",               branch => $BUILD_BRANCH, },
   { name => "zm-versioncheck-utilities",           branch => $BUILD_BRANCH, },
   { name => "zm-viewmail-admin-zimlet",            branch => $BUILD_BRANCH, },
   { name => "zm-web-client",                       branch => $BUILD_BRANCH,},
   { name => "zm-webclient-portal-example",         branch => $BUILD_BRANCH, },
   { name => "zm-zcs",                              branch => $BUILD_BRANCH, },
   { name => "zm-zcs-lib",                          branch => $BUILD_BRANCH, },
   { name => "zm-ssdb-ephemeral-store",             branch => $BUILD_BRANCH, },
   { name => "zm-zimlets",                          branch => $BUILD_BRANCH, },
);
